/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Compose a system prompt using the cached version for better performance */
export declare function composeSystemPrompt(request: string): string
/** List available domain modules */
export declare function listAvailableDomains(): Array<string>
/** List available behavior modules   */
export declare function listAvailableBehaviors(): Array<string>
/** Check if the native bindings are available (always true) */
export declare function isAvailable(): boolean
/** Get status information as JSON string */
export declare function getStatus(): string
